/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js'
import NFTContractArtifactJson from './raven_nft_contract-NFT.json' assert { type: 'json' }
export const NFTContractArtifact = loadContractArtifact(
  NFTContractArtifactJson as NoirCompiledContract
)

export type NFTTransfer = {
  from: AztecAddressLike
  to: AztecAddressLike
  token_id: FieldLike
  collection: AztecAddressLike
}

export type MetadataUpdate = {
  token_id: FieldLike
}

export type ListingSold = {
  token_id: FieldLike
  seller: AztecAddressLike
  buyer: AztecAddressLike
  collection: AztecAddressLike
}

export type ListingCreated = {
  token_id: FieldLike
  seller: AztecAddressLike
  price: bigint | number
  collection: AztecAddressLike
}

export type ListingCancelled = {
  token_id: FieldLike
  seller: AztecAddressLike
}

/**
 * Type-safe interface for contract NFT;
 */
export class NFTContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, NFTContractArtifact, wallet)
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(address, NFTContract.artifact, wallet) as Promise<NFTContract>
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(
    wallet: Wallet,
    admin: AztecAddressLike,
    name: string,
    symbol: string,
    erc20_token: AztecAddressLike,
    is_mint_public: boolean,
    mint_limit_per_wallet: bigint | number,
    max_supply: bigint | number,
    mint_price: bigint | number
  ) {
    return new DeployMethod<NFTContract>(
      PublicKeys.default(),
      wallet,
      NFTContractArtifact,
      NFTContract.at,
      Array.from(arguments).slice(1)
    )
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike,
    name: string,
    symbol: string,
    erc20_token: AztecAddressLike,
    is_mint_public: boolean,
    mint_limit_per_wallet: bigint | number,
    max_supply: bigint | number,
    mint_price: bigint | number
  ) {
    return new DeployMethod<NFTContract>(
      publicKeys,
      wallet,
      NFTContractArtifact,
      NFTContract.at,
      Array.from(arguments).slice(2)
    )
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof NFTContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<NFTContract['methods'][M]>
  ) {
    return new DeployMethod<NFTContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      NFTContractArtifact,
      NFTContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor'
    )
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return NFTContractArtifact
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(NFTContractArtifactJson as NoirCompiledContract)
  }

  public static get storage(): ContractStorageLayout<
    | 'symbol'
    | 'name'
    | 'admin'
    | 'minters'
    | 'private_nfts'
    | 'nft_exists'
    | 'public_owners'
    | 'token_uris'
    | 'base_uri'
    | 'erc20_token'
    | 'listings'
    | 'fee_recipient'
    | 'owner_nft_count'
    | 'nft_mint_count'
    | 'total_nft_count'
    | 'is_mint_public'
    | 'mint_limit_per_wallet'
    | 'max_supply'
    | 'mint_price'
  > {
    return {
      symbol: {
        slot: new Fr(1n),
      },
      name: {
        slot: new Fr(3n),
      },
      admin: {
        slot: new Fr(5n),
      },
      minters: {
        slot: new Fr(6n),
      },
      private_nfts: {
        slot: new Fr(7n),
      },
      nft_exists: {
        slot: new Fr(8n),
      },
      public_owners: {
        slot: new Fr(9n),
      },
      token_uris: {
        slot: new Fr(10n),
      },
      base_uri: {
        slot: new Fr(11n),
      },
      erc20_token: {
        slot: new Fr(13n),
      },
      listings: {
        slot: new Fr(15n),
      },
      fee_recipient: {
        slot: new Fr(16n),
      },
      owner_nft_count: {
        slot: new Fr(17n),
      },
      nft_mint_count: {
        slot: new Fr(18n),
      },
      total_nft_count: {
        slot: new Fr(19n),
      },
      is_mint_public: {
        slot: new Fr(20n),
      },
      mint_limit_per_wallet: {
        slot: new Fr(21n),
      },
      max_supply: {
        slot: new Fr(22n),
      },
      mint_price: {
        slot: new Fr(23n),
      },
    } as ContractStorageLayout<
      | 'symbol'
      | 'name'
      | 'admin'
      | 'minters'
      | 'private_nfts'
      | 'nft_exists'
      | 'public_owners'
      | 'token_uris'
      | 'base_uri'
      | 'erc20_token'
      | 'listings'
      | 'fee_recipient'
      | 'owner_nft_count'
      | 'nft_mint_count'
      | 'total_nft_count'
      | 'is_mint_public'
      | 'mint_limit_per_wallet'
      | 'max_supply'
      | 'mint_price'
    >
  }

  public static get notes(): ContractNotes<'UintNote' | 'NFTNote'> {
    return {
      UintNote: {
        id: new NoteSelector(0),
      },
      NFTNote: {
        id: new NoteSelector(1),
      },
    } as ContractNotes<'UintNote' | 'NFTNote'>
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    /** buy(token_id: field, nonce: field) */
    buy: ((token_id: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** cancel_authwit(inner_hash: field) */
    cancel_authwit: ((inner_hash: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** cancel_listing(token_id: field) */
    cancel_listing: ((token_id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** constructor(admin: struct, name: string, symbol: string, erc20_token: struct, is_mint_public: boolean, mint_limit_per_wallet: integer, max_supply: integer, mint_price: integer) */
    constructor: ((
      admin: AztecAddressLike,
      name: string,
      symbol: string,
      erc20_token: AztecAddressLike,
      is_mint_public: boolean,
      mint_limit_per_wallet: bigint | number,
      max_supply: bigint | number,
      mint_price: bigint | number
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** create_listing(token_id: field, price: integer) */
    create_listing: ((token_id: FieldLike, price: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** finalize_transfer_to_private(token_id: field, partial_note: struct) */
    finalize_transfer_to_private: ((
      token_id: FieldLike,
      partial_note: { commitment: FieldLike }
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** get_max_supply() */
    get_max_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** get_mint_price() */
    get_mint_price: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** get_nft_count(owner: struct) */
    get_nft_count: ((owner: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** get_private_nfts(owner: struct, page_index: integer) */
    get_private_nfts: ((
      owner: AztecAddressLike,
      page_index: bigint | number
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** get_public_nfts(owner: struct, offset: integer) */
    get_public_nfts: ((
      owner: AztecAddressLike,
      offset: bigint | number
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** get_token_uri(token_id: field) */
    get_token_uri: ((token_id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** get_total_nft_count() */
    get_total_nft_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** is_mint_public() */
    is_mint_public: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** is_minter(minter: struct) */
    is_minter: ((minter: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** mint(to: struct, token_uri_parts: array, nonce: field) */
    mint: ((
      to: AztecAddressLike,
      token_uri_parts: string[],
      nonce: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** owner_of(token_id: field) */
    owner_of: ((token_id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** prepare_private_balance_increase(to: struct) */
    prepare_private_balance_increase: ((to: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** private_get_name() */
    private_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** private_get_symbol() */
    private_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** public_get_name() */
    public_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** public_get_symbol() */
    public_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** set_admin(new_admin: struct) */
    set_admin: ((new_admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** set_base_uri(base_uri_parts: array) */
    set_base_uri: ((base_uri_parts: string[]) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** set_fee_recipient(recipient: struct) */
    set_fee_recipient: ((recipient: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** set_mint_limit_per_wallet(new_mint_limit: integer) */
    set_mint_limit_per_wallet: ((new_mint_limit: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** set_mint_price(new_price: integer) */
    set_mint_price: ((new_price: bigint | number) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** set_mint_type(is_mint_public: boolean) */
    set_mint_type: ((is_mint_public: boolean) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** set_minter(minter: struct, approve: boolean) */
    set_minter: ((minter: AztecAddressLike, approve: boolean) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** set_token_uri(token_id: field, token_uri_parts: array) */
    set_token_uri: ((
      token_id: FieldLike,
      token_uri_parts: string[]
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>

    /** transfer_in_private(from: struct, to: struct, token_id: field, nonce: field) */
    transfer_in_private: ((
      from: AztecAddressLike,
      to: AztecAddressLike,
      token_id: FieldLike,
      nonce: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** transfer_in_public(from: struct, to: struct, token_id: field, nonce: field) */
    transfer_in_public: ((
      from: AztecAddressLike,
      to: AztecAddressLike,
      token_id: FieldLike,
      nonce: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** transfer_to_private(to: struct, token_id: field) */
    transfer_to_private: ((
      to: AztecAddressLike,
      token_id: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>

    /** transfer_to_public(from: struct, to: struct, token_id: field, nonce: field) */
    transfer_to_public: ((
      from: AztecAddressLike,
      to: AztecAddressLike,
      token_id: FieldLike,
      nonce: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, 'selector'>
  }

  public static get events(): {
    NFTTransfer: { abiType: AbiType; eventSelector: EventSelector; fieldNames: string[] }
    MetadataUpdate: { abiType: AbiType; eventSelector: EventSelector; fieldNames: string[] }
    ListingSold: { abiType: AbiType; eventSelector: EventSelector; fieldNames: string[] }
    ListingCreated: { abiType: AbiType; eventSelector: EventSelector; fieldNames: string[] }
    ListingCancelled: { abiType: AbiType; eventSelector: EventSelector; fieldNames: string[] }
  } {
    return {
      NFTTransfer: {
        abiType: {
          kind: 'struct',
          fields: [
            {
              name: 'from',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
            {
              name: 'to',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
            {
              name: 'token_id',
              type: {
                kind: 'field',
              },
            },
            {
              name: 'collection',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
          ],
          path: 'NFT::NFTTransfer',
        },
        eventSelector: EventSelector.fromString('0xd072c00d'),
        fieldNames: ['from', 'to', 'token_id', 'collection'],
      },
      MetadataUpdate: {
        abiType: {
          kind: 'struct',
          fields: [
            {
              name: 'token_id',
              type: {
                kind: 'field',
              },
            },
          ],
          path: 'NFT::MetadataUpdate',
        },
        eventSelector: EventSelector.fromString('0x9a627f82'),
        fieldNames: ['token_id'],
      },
      ListingSold: {
        abiType: {
          kind: 'struct',
          fields: [
            {
              name: 'token_id',
              type: {
                kind: 'field',
              },
            },
            {
              name: 'seller',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
            {
              name: 'buyer',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
            {
              name: 'collection',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
          ],
          path: 'NFT::ListingSold',
        },
        eventSelector: EventSelector.fromString('0x75f51d64'),
        fieldNames: ['token_id', 'seller', 'buyer', 'collection'],
      },
      ListingCreated: {
        abiType: {
          kind: 'struct',
          fields: [
            {
              name: 'token_id',
              type: {
                kind: 'field',
              },
            },
            {
              name: 'seller',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
            {
              name: 'price',
              type: {
                kind: 'integer',
                sign: 'unsigned',
                width: 128,
              },
            },
            {
              name: 'collection',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
          ],
          path: 'NFT::ListingCreated',
        },
        eventSelector: EventSelector.fromString('0x90ad5c56'),
        fieldNames: ['token_id', 'seller', 'price', 'collection'],
      },
      ListingCancelled: {
        abiType: {
          kind: 'struct',
          fields: [
            {
              name: 'token_id',
              type: {
                kind: 'field',
              },
            },
            {
              name: 'seller',
              type: {
                kind: 'struct',
                fields: [
                  {
                    name: 'inner',
                    type: {
                      kind: 'field',
                    },
                  },
                ],
                path: 'authwit::aztec::protocol_types::address::aztec_address::AztecAddress',
              },
            },
          ],
          path: 'NFT::ListingCancelled',
        },
        eventSelector: EventSelector.fromString('0x00f84ac3'),
        fieldNames: ['token_id', 'seller'],
      },
    }
  }
}
